//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::categories::Entity as Categories;
pub use super::product_categories::Entity as ProductCategories;
pub use super::products::Entity as Products;
